### ISSUE TITLE
Deploy CustomMetaData Does Not Seem To Work Any Longer

### ISSUE THREAD

**Issue by veaux** [shunkosa/sfdx-cmdt-plugin#4]
sfdx force:source:deploy -m customMetadata on the converted file no longer seems to work as of sfdx 7.43.1. File successfully converts but sfdx is not recognizing the file for deploy or push.

**Comment by shunkosa** [comment]
@veaux Sorry for the delay & thank you for the feedback! I'm afraid it was a problem of cli itself. Could you please try the latest release? (7.48.0)

**Comment by veaux** [comment]
Looks like I skipped 7.48, but on 7.49 I don't see any difference, still not recognizing. Tried sfdx:push and sfdx:deploy

**Comment by shunkosa** [comment]
Could you please post the medadata here?

**Comment by veaux** [comment]
This is one record
[mdt.txt](https://github.com/shunkosa/sfdx-cmdt-plugin/files/4324631/mdt.txt)

**Comment by veaux** [comment]
Got the answer on Success Community, sorry for the issue. The recent problem was that the default .forceignore from GitHub includes *.md files to ignore. So it was missing these. After removing that it now works as designed. Thanks! Also, not sure if you already know this but the product team for Custom Metadata said they are releasing an extension in 1-2 months to do this. Hoping you've been working with them since this worked so well.
